class Support::AssistedPolicy
  READ = %w[index show new edit].freeze
  CRUD = (READ + %w[create update]).freeze
  # Lista explícita: novas rotas não ganham acesso assistido automaticamente.
  ACTIONS = {
    "admin/dashboard" => %w[index section],
    "admin/habitations" => CRUD + %w[operational_hub gallery confirm_owner_contact duplicate filter_inspector proprietor_options search_by_code bulk_publish bulk_publish_eligibility share_selection generate_ai_preview format_ai_suggestion apply_ai_suggestion],
    "admin/habitation_duplicates" => %w[check],
    "admin/habitation_media" => %w[show update modal upload reorder visibility ambiente organize share],
    "admin/leads" => CRUD + %w[kanban_column pwa_leads_page distribution_queue lead_pool attend toggle_favorite log_contact reprocess_interest simulate_interest interest_intelligence open_whatsapp_conversation activate_whatsapp_template share_properties suggest_properties archive close_deal schedule_activity],
    "admin/lead_pipelines" => %w[create update],
    "admin/lead_statuses" => %w[index documentation automation_executions bulk_update],
    "admin/lead_labels" => %w[index create update toggle],
    "admin/property_interests" => %w[create search],
    "admin/proprietors" => CRUD + %w[quick_update quick_search quick_create],
    "admin/tasks" => %w[index create update complete],
    "admin/appointments" => %w[index create update],
    "admin/proposals" => CRUD + %w[send_proposal pdf],
    "admin/automation_events" => %w[index reprocess ignore],
    "admin/automation_workflows" => %w[index new create show builder save_draft publish simulate],
    "admin/automation_rules" => CRUD + %w[toggle_active simulate create_example],
    "admin/whatsapp_campaigns" => CRUD + %w[documentation preview_audience preview_template send_test start pause resume cancel cancel_pending retry_failed status],
    "admin/whatsapp_templates" => %w[index show new_campaign],
    "admin/whatsapp_campaign_recipients" => %w[index],
    "admin/whatsapp_campaign_unsubscribes" => %w[index reenable],
    "admin/whatsapp_inbox" => %w[index show send_message media react toggle_pin toggle_star forward_message add_to_notes],
    "admin/notification_template_settings" => %w[create update],
    "admin/distribution_rules" => CRUD + %w[toggle_active reorder_agents],
    "admin/habitation_intakes" => CRUD + %w[proprietor_lookup publish submit_for_review approve return_to_broker release_to_site],
    "admin/captacoes" => %w[dashboard update_dashboard_title],
    "admin/captacao_goals" => CRUD,
    "admin/stores" => CRUD + %w[geocode],
    "admin/field/check_ins" => %w[index show force_check_out],
    "admin/field/manual_checkin_requests" => %w[index show approve reject],
    "admin/field/audit_logs" => %w[index show],
    "admin/field_settings" => %w[edit update block_agent unblock_agent],
    "admin/access_audit_logs" => %w[index],
    "admin/data_export_audit_logs" => %w[index],
    "admin/presentation_audit_logs" => %w[index],
    "admin/user_activity_sessions" => %w[index show],
    "admin/admin_users" => %w[index show hierarchy],
    "admin/attribute_options" => %w[index create update],
    "admin/marketing_campaigns" => CRUD,
    "admin/seo_dashboard" => %w[index],
    "admin/marketing_opportunities" => %w[index],
    "admin/marketing_properties" => %w[index],
    "admin/marketing_alerts" => %w[index],
    "admin/marketing_tools" => %w[index],
    "admin/seo_settings" => CRUD + %w[update_strategy discover generate_ai toggle],
    "admin/seo_redirects" => %w[index create update],
    "admin/banners" => CRUD,
    "admin/home_sections" => CRUD + %w[toggle_active update_order],
    "admin/home_section_items" => CRUD,
    "admin/landing_pages" => CRUD + %w[preview],
    "admin/home_settings" => %w[edit update],
    "admin/contact_settings" => %w[edit update],
    "admin/footer_settings" => %w[edit update],
    "admin/public_site_profiles" => %w[edit update],
    "admin/presentation_cards" => CRUD,
    "admin/manifests" => %w[show],
    "field/home" => %w[show],
    "field/stores" => %w[discover],
    "field/check_ins" => %w[new create check_out],
    "field/location_pings" => %w[create],
    "field/manual_checkin_requests" => %w[new create],
    "field/property_searches" => %w[show create select preview],
    "field/property_share_collections" => %w[create],
    "field/manifests" => %w[show],
    "support/tickets" => %w[index show attachment updates],
    "support/access_grants" => %w[destroy]
  }.freeze
  def self.allowed?(controller, action)
    ACTIONS.fetch(controller, []).include?(action)
  end
end
