// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AdvancedFiltersController from "controllers/advanced_filters_controller"
application.register("advanced-filters", AdvancedFiltersController)

import AiPreviewController from "controllers/ai_preview_controller"
application.register("ai-preview", AiPreviewController)

import AttributeManagerController from "controllers/attribute_manager_controller"
application.register("attribute-manager", AttributeManagerController)

import AutocompleteController from "controllers/autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import CardSwiperController from "controllers/card_swiper_controller"
application.register("card-swiper", CardSwiperController)

import BrokerShareController from "controllers/broker_share_controller"
application.register("broker-share", BrokerShareController)

import BulkPublishController from "controllers/bulk_publish_controller"
application.register("bulk-publish", BulkPublishController)

import CategoryFilterController from "controllers/category_filter_controller"
application.register("category-filter", CategoryFilterController)

import CaptacaoPhotosController from "controllers/captacao_photos_controller"
application.register("captacao-photos", CaptacaoPhotosController)

import CepLookupController from "controllers/cep_lookup_controller"
application.register("cep-lookup", CepLookupController)

import CepSearchController from "controllers/cep_search_controller"
application.register("cep-search", CepSearchController)

import ClickableCardController from "controllers/clickable_card_controller"
application.register("clickable-card", ClickableCardController)

import ClipboardController from "controllers/clipboard_controller"
application.register("clipboard", ClipboardController)

import CodeSearchController from "controllers/code_search_controller"
application.register("code-search", CodeSearchController)

import CollapseController from "controllers/collapse_controller"
application.register("collapse", CollapseController)

import CurrencyMaskController from "controllers/currency_mask_controller"
application.register("currency-mask", CurrencyMaskController)

import DistributionRuleController from "controllers/distribution_rule_controller"
application.register("distribution-rule", DistributionRuleController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import DwvSyncStatusController from "controllers/dwv_sync_status_controller"
application.register("dwv-sync-status", DwvSyncStatusController)

import DynamicListController from "controllers/dynamic_list_controller"
application.register("dynamic-list", DynamicListController)

import FavoritesController from "controllers/favorites_controller"
application.register("favorites", FavoritesController)

import FancyboxGalleryController from "controllers/fancybox_gallery_controller"
application.register("fancybox-gallery", FancyboxGalleryController)

import FiltersController from "controllers/filters_controller"
application.register("filters", FiltersController)

import HabitationBrokersController from "controllers/habitation_brokers_controller"
application.register("habitation-brokers", HabitationBrokersController)

import HabitationFormController from "controllers/habitation_form_controller"
application.register("habitation-form", HabitationFormController)

import HabitationDuplicateCheckController from "controllers/habitation_duplicate_check_controller"
application.register("habitation-duplicate-check", HabitationDuplicateCheckController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import HeroSliderController from "controllers/hero_slider_controller"
application.register("hero-slider", HeroSliderController)

import ImagePreviewController from "controllers/image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ImageMigrationStatusController from "controllers/image_migration_status_controller"
application.register("image-migration-status", ImageMigrationStatusController)

import LeadCaptureController from "controllers/lead_capture_controller"
application.register("lead-capture", LeadCaptureController)

import LgpdConsentController from "controllers/lgpd_consent_controller"
application.register("lgpd-consent", LgpdConsentController)

import LeadKanbanController from "controllers/lead_kanban_controller"
application.register("lead-kanban", LeadKanbanController)

import LocationFilterController from "controllers/location_filter_controller"
application.register("location-filter", LocationFilterController)

import MaskController from "controllers/mask_controller"
application.register("mask", MaskController)

import MarketingTrackerController from "controllers/marketing_tracker_controller"
application.register("marketing-tracker", MarketingTrackerController)

import MetaRulesController from "controllers/meta_rules_controller"
application.register("meta-rules", MetaRulesController)

import NavbarController from "controllers/navbar_controller"
application.register("navbar", NavbarController)

import NestedFormController from "controllers/nested_form_controller"
application.register("nested-form", NestedFormController)

import PhotoCarouselController from "controllers/photo_carousel_controller"
application.register("photo-carousel", PhotoCarouselController)

import PhotoGalleryController from "controllers/photo_gallery_controller"
application.register("photo-gallery", PhotoGalleryController)

import PhotoUploadController from "controllers/photo_upload_controller"
application.register("photo-upload", PhotoUploadController)

import PropertyCarouselController from "controllers/property_carousel_controller"
application.register("property-carousel", PropertyCarouselController)

import PropertyPagePreviewController from "controllers/property_page_preview_controller"
application.register("property-page-preview", PropertyPagePreviewController)

import WatermarkPreviewController from "controllers/watermark_preview_controller"
application.register("watermark-preview", WatermarkPreviewController)

import ProprietorTableController from "controllers/proprietor_table_controller"
application.register("proprietor-table", ProprietorTableController)

import RentCalculatorController from "controllers/rent_calculator_controller"
application.register("rent-calculator", RentCalculatorController)

import ScrollVisibilityController from "controllers/scroll_visibility_controller"
application.register("scroll-visibility", ScrollVisibilityController)

import SearchFormController from "controllers/search_form_controller"
application.register("search-form", SearchFormController)

import SearchTabsController from "controllers/search_tabs_controller"
application.register("search-tabs", SearchTabsController)

import ShareController from "controllers/share_controller"
application.register("share", ShareController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import SaveStateController from "controllers/save_state_controller"
application.register("save-state", SaveStateController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)

import StoreMapPickerController from "controllers/store_map_picker_controller"
application.register("store-map-picker", StoreMapPickerController)

import FieldGeolocationController from "controllers/field/geolocation_controller"
application.register("field-geolocation", FieldGeolocationController)

import FieldCheckinController from "controllers/field/checkin_controller"
application.register("field-checkin", FieldCheckinController)

import FieldPingSenderController from "controllers/field/ping_sender_controller"
application.register("field-ping-sender", FieldPingSenderController)

import VistaSyncStatusController from "controllers/vista_sync_status_controller"
application.register("vista-sync-status", VistaSyncStatusController)

import OptionPickerController from "controllers/option_picker_controller"
application.register("option-picker", OptionPickerController)

import CollapsibleCountController from "controllers/collapsible_count_controller"
application.register("collapsible-count", CollapsibleCountController)

import TagInputController from "controllers/tag_input_controller"
application.register("tag-input", TagInputController)

import TeamRulesController from "controllers/team_rules_controller"
application.register("team-rules", TeamRulesController)

import TomSelectController from "controllers/tom_select_controller"
application.register("tom-select", TomSelectController)

import TransactionToggleController from "controllers/transaction_toggle_controller"
application.register("transaction-toggle", TransactionToggleController)
