source "https://rubygems.org"

ruby "3.2.3"

gem "activerecord", "~> 7.1"
gem "dotenv", "~> 3.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"
gem "rake", "~> 13.2"
gem "sinatra", "~> 4.0"

group :test do
  gem "rack-test", "~> 2.1"
  gem "rspec", "~> 3.13"
  gem "webmock", "~> 3.23"
end
