development:
  url: <%= ENV.fetch("DATABASE_URL", "postgres://localhost/unitymob_whatsapp_gateway_development") %>

test:
  url: <%= ENV.fetch("DATABASE_URL", "postgres://localhost/unitymob_whatsapp_gateway_test") %>

production:
  url: <%= ENV["DATABASE_URL"] %>
