class BackfillCategoryMismatchedHabitationSlugs < ActiveRecord::Migration[7.0]
  class MigrationHabitation < ActiveRecord::Base
    self.table_name = "habitations"
  end

  def up
    MigrationHabitation.where.not(slug: [nil, ""]).find_each do |habitation|
      next if habitation.tipo.to_s == "Empreendimento"
      next if habitation.categoria.blank? || habitation.codigo.blank?

      category_prefix = habitation.categoria.to_s.parameterize
      next if category_prefix.blank?

      slug_without_code = habitation.slug.to_s.sub(/-#{Regexp.escape(habitation.codigo.to_s)}\z/, "")
      next if slug_without_code.blank? || slug_without_code.start_with?(category_prefix)

      habitation.update_columns(slug: nil, updated_at: Time.current)
    end
  end

  def down
    # Slugs are regenerated by FriendlyId when records are saved.
  end
end
