source "https://rubygems.org"
ruby "3.2.3"
gem "rails", "~> 7.1.2"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "sprockets-rails"
gem "turbo-rails"
gem "bcrypt", "~> 3.1.7"
gem "rotp", "~> 6.3"
gem "rqrcode", "~> 2.2"
gem "solid_queue"
gem "aws-sdk-s3", require: false
gem "dotenv-rails"
gem "rack-attack"
gem "rails-i18n"
group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "mina"
end
