local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
private_spaces:
  service: S3
  access_key_id: <%= ENV["SUPPORT_STORAGE_KEY"] %>
  secret_access_key: <%= ENV["SUPPORT_STORAGE_SECRET"] %>
  region: <%= ENV["SUPPORT_STORAGE_REGION"] %>
  bucket: <%= ENV["SUPPORT_STORAGE_BUCKET"] %>
  endpoint: <%= ENV["SUPPORT_STORAGE_ENDPOINT"] %>
  public: false

support_private:
<% if Rails.env.production? %>
  service: S3
  access_key_id: <%= ENV["SUPPORT_STORAGE_KEY"] %>
  secret_access_key: <%= ENV["SUPPORT_STORAGE_SECRET"] %>
  region: <%= ENV["SUPPORT_STORAGE_REGION"] %>
  bucket: <%= ENV["SUPPORT_STORAGE_BUCKET"] %>
  endpoint: <%= ENV["SUPPORT_STORAGE_ENDPOINT"] %>
  public: false
<% else %>
  service: Disk
  root: <%= Rails.root.join("storage/support") %>
<% end %>
